# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(default='', max_length=255)),
                ('description', models.TextField(default='', verbose_name='About')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'verbose_name': 'Product',
            },
        ),
    ]
