# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20161108_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_like',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
